// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// @inject_field: age int
// @inject_field: spouse *Human
// @inject_field: IgnoreMe
type Human struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`

	// custom fields
	age int
	spouse *Human
}

// custom fields getter/setter
func (m *Human) Age() int {
	return m.age
}
func (m *Human) SetAge(in int){
	m.age = in
}
func (m *Human) Spouse() *Human {
	return m.spouse
}
func (m *Human) SetSpouse(in *Human){
	m.spouse = in
}

func (m *Human) Reset()         { *m = Human{} }
func (m *Human) String() string { return proto.CompactTextString(m) }
func (*Human) ProtoMessage()    {}
func (*Human) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *Human) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Human.Unmarshal(m, b)
}
func (m *Human) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Human.Marshal(b, m, deterministic)
}
func (m *Human) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Human.Merge(m, src)
}
func (m *Human) XXX_Size() int {
	return xxx_messageInfo_Human.Size(m)
}
func (m *Human) XXX_DiscardUnknown() {
	xxx_messageInfo_Human.DiscardUnknown(m)
}

var xxx_messageInfo_Human proto.InternalMessageInfo

func (m *Human) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// @inject_field: model string
type Robot struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`

	// custom fields
	model string
}

// custom fields getter/setter
func (m *Robot) Model() string {
	return m.model
}
func (m *Robot) SetModel(in string){
	m.model = in
}

func (m *Robot) Reset()         { *m = Robot{} }
func (m *Robot) String() string { return proto.CompactTextString(m) }
func (*Robot) ProtoMessage()    {}
func (*Robot) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *Robot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Robot.Unmarshal(m, b)
}
func (m *Robot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Robot.Marshal(b, m, deterministic)
}
func (m *Robot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Robot.Merge(m, src)
}
func (m *Robot) XXX_Size() int {
	return xxx_messageInfo_Robot.Size(m)
}
func (m *Robot) XXX_DiscardUnknown() {
	xxx_messageInfo_Robot.DiscardUnknown(m)
}

var xxx_messageInfo_Robot proto.InternalMessageInfo

func (m *Robot) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Alien struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Alien) Reset()         { *m = Alien{} }
func (m *Alien) String() string { return proto.CompactTextString(m) }
func (*Alien) ProtoMessage()    {}
func (*Alien) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *Alien) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alien.Unmarshal(m, b)
}
func (m *Alien) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alien.Marshal(b, m, deterministic)
}
func (m *Alien) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alien.Merge(m, src)
}
func (m *Alien) XXX_Size() int {
	return xxx_messageInfo_Alien.Size(m)
}
func (m *Alien) XXX_DiscardUnknown() {
	xxx_messageInfo_Alien.DiscardUnknown(m)
}

var xxx_messageInfo_Alien proto.InternalMessageInfo

func (m *Alien) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Human)(nil), "pb.Human")
	proto.RegisterType((*Robot)(nil), "pb.Robot")
	proto.RegisterType((*Alien)(nil), "pb.Alien")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 86 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x92, 0xe6, 0x62, 0xf5, 0x28,
	0xcd, 0x4d, 0xcc, 0x13, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x02, 0xb3, 0x41, 0x92, 0x41, 0xf9, 0x49, 0xf9, 0x25, 0xb8, 0x24, 0x1d, 0x73, 0x32,
	0x53, 0xb1, 0xea, 0x4c, 0x62, 0x03, 0xdb, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x9d,
	0x3a, 0xe6, 0x6f, 0x00, 0x00, 0x00,
}
